// ESM adaptation of the graph reduction/search used by sfinder-strict-minimal (MIT).
function contain(a,b){for(const x of b)if(!a.has(x))return false;return true}function equal(a,b){return a.size===b.size&&contain(a,b)}function first(s){return s.values().next().value}
export function strictMinimal(coverage){const nodeMap=new Map();const edges=[];for(const[pattern,keys]of coverage){const nodes=new Set();for(const key of keys){let n=nodeMap.get(key);if(!n){n={key,edges:new Set(),color:0,alter:[],redundant:false};nodeMap.set(key,n)}nodes.add(n)}if(nodes.size)edges.push({pattern,nodes,color:0,redundant:false})}edges.sort((a,b)=>a.nodes.size-b.nodes.size);for(const e of edges){if(e.redundant)continue;for(const sib of first(e.nodes).edges){if(e!==sib&&contain(sib.nodes,e.nodes))sib.redundant=true}for(const n of e.nodes)n.edges.add(e)}// rebuild redundancy correctly after edges attached
for(const e of edges)e.redundant=false;for(const e of edges){if(e.redundant)continue;const n=first(e.nodes);if(!n)continue;for(const sib of n.edges){if(e!==sib&&contain(sib.nodes,e.nodes))sib.redundant=true}}
const cleanEdges=edges.filter(e=>!e.redundant);for(const n of nodeMap.values())for(const e of[...n.edges])if(e.redundant)n.edges.delete(e);const nodes=[...nodeMap.values()].filter(n=>n.edges.size);nodes.sort((a,b)=>a.edges.size-b.edges.size);for(const n of nodes){if(n.redundant)continue;for(const sib of first(n.edges).nodes){if(sib!==n&&equal(n.edges,sib.edges)){sib.redundant=true;n.alter.push(sib)}}}for(const e of cleanEdges)for(const n of[...e.nodes])if(n.redundant)e.nodes.delete(n);
let best=Infinity,sets=[],current=[];function dig(i){if(current.length>best)return;if(i>=cleanEdges.length){if(current.length<best){best=current.length;sets=[]}sets.push(current.map(n=>n.key));return}const e=cleanEdges[i];if(e.color){dig(i+1);return}for(const n of e.nodes){n.color++;if(n.color>1)continue;current.push(n);for(const se of n.edges)se.color++;dig(i+1);current.pop();for(const se of n.edges)se.color--;}for(const n of e.nodes)n.color--;}dig(0);return{count:best,sets}}

// SFinder path emits equivalent-coverage tilings in a deterministic order.
// Rust HashMap enumeration is intentionally unordered, so normalize the mask key
// order before graph construction to preserve sfinder-strict-minimal tie selection.
export function canonicalSolutionOrder(solutions){return [...solutions].sort((a,b)=>a.key===b.key?0:(a.key>b.key?-1:1))}
